//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int AboutUsID { get; set; }
        public string OurStory { get; set; }
        public string OurStoryImage { get; set; }
        public string OurVision1 { get; set; }
        public string OurVision2 { get; set; }
        public string OurVision3 { get; set; }
        public string OurVision4 { get; set; }
        public string OurMenu { get; set; }
        public string OurMenuImage1 { get; set; }
        public string OurMenuImage2 { get; set; }
        public string OurMenuImage3 { get; set; }
        public string OurMenuImage4 { get; set; }
    }
}
