//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTable
    {
        public int BookingTableID { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> NumberCustomer { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.TimeSpan> BookingTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
