//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int FooterID { get; set; }
        public string OpenTime1 { get; set; }
        public string OpenTime2 { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string FacebookLink { get; set; }
        public string InstaLink { get; set; }
    }
}
