//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsNew
    {
        public Nullable<int> TagsID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public int TagsNewsID { get; set; }
    
        public virtual News News { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
